import application.ChartExamples;

/*
 * These charts are generated by xhcart:
 * https://knowm.org/open-source/xchart/xchart-example-code/
 */
public class ChartExamplesCLI {

    public static void main(String[] args) {
        new ChartExamples();
    }
}
