package application;

import charts.*;

import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/*
 * These charts are generated by xhcart:
 * https://knowm.org/open-source/xchart/xchart-example-code/
 */
public class ChartExamples {
    Scanner inputScanner = new Scanner(System.in);
    static List<Runnable> charts;

    public ChartExamples() {

        charts = Arrays.asList(
                new SimpleChart(),
                new AreaChart(),
                new AreaLineChart(),
                new MatrixChart(),
                new LogarithmicChart(),
                new PieChart2(),
                new ScatterChart2(),
                new StickChart2(),
                new BasicBarChart(),
                new RealTimeChart(),
                new DonutChart(),
                new HistogramChart(),
                new BubbleChart2()
        );

        displayAvailableCharts();

        while(true) {
            Runnable chart = askUserForChart();

            if(chart == null){
                System.exit(0);
            }

            chart.run();
        }
    }

    private Runnable askUserForChart(){
        Runnable selectedChart = null;

        System.out.print("Select a chart to display (1-" + charts.size() + ") or E to exit: ");
        String response = inputScanner.nextLine();

        if( !response.equalsIgnoreCase("e")) {

            while (true) {
                try {

                    // User selection started at 1, not 0
                    int userSelection = Integer.parseInt(response);
                    selectedChart = charts.get(userSelection - 1);
                    break;

                } catch (NumberFormatException e) {
                    System.out.println("Please enter a number from 1-" + charts.size());
                    response = inputScanner.nextLine();
                }
            }
        }

        return selectedChart;
    }

    private void displayAvailableCharts(){
        for (int i = 0; i < charts.size(); i++) {
            System.out.println((i + 1) + ". " + charts.get(i));
        }
    }
}
